### ISSUE TITLE
Data-layer pods pending during deployment to kubernetes

### ISSUE THREAD

**Issue by hpthai7** [knix-microfunctions/knix#41] opened 2020-06-16 10:21 UTC
Hello,

## Context

The data-layer statefulset has a podAntiAffinity rule, imposing the 1-1 relation between its pods and physical K8s nodes.

When the number of replicas of data-layer component surpasses the number of available physical nodes. The surplus replicas will then be stuck in the Pending state.

For example, we have two hospitable nodes in our cluster. When data-layer component creates three replicas, one always stays in Pending state.

Why is this rule applied? Should the podAffinityRule be loosened?

```shell
$ k get pods
NAME                      READY   STATUS             RESTARTS   AGE
dl-mfn-0                  1/1     Running            0          12m
dl-mfn-1                  0/1     Pending            0          3m8s
dl-mfn-2                  1/1     Running            0          12m

$ k describe pods dl-mfn-1
Name:           dl-mfn-1
Namespace:      knix-test
Priority:       0
Node:           <none>
Labels:         app=microfunctions-datalayer
                controller-revision-hash=dl-mfn-7f4cff64cf
                release=mfn
                statefulset.kubernetes.io/pod-name=dl-mfn-1
Annotations:    kubernetes.io/psp: restricted
                seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/dl-mfn
Containers:
  datalayer:
    Image:      slfg92.rcs.de.alcatel-lucent.com:443/microfn/datalayer:latest
    Port:       4998/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:      100m
      memory:   200Mi
    Readiness:  tcp-socket :4998 delay=0s timeout=30s period=10s #success=1 #failure=10
    Environment:
      RIAK_CONNECT:        rk-mfn.knix-test.svc.cluster.local:8087
      DATALAYER_BIND:      0.0.0.0:4998
      ALL_DATALAYER_BIND:  dl-mfn1-0.datalayer.knix-test.svc.cluster.local:4998,dl-mfn1-1.datalayer.knix-test.svc.cluster.local:4998,dl-mfn1-2.datalayer.knix-test.svc.cluster.  local:4998
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-vbh6g (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-vbh6g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-vbh6g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods   anti-affinity rules, 2 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods   anti-affinity rules, 2 node(s) had taints that the pod didn't tolerate.


k describe pods dl-mfn-1
Name:           dl-mfn-1
Namespace:      knix-test
Priority:       0
Node:           <none>
Labels:         app=microfunctions-datalayer
                controller-revision-hash=dl-mfn-7f4cff64cf
                release=mfn
                statefulset.kubernetes.io/pod-name=dl-mfn-1
Annotations:    kubernetes.io/psp: restricted
                seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/dl-mfn
Containers:
  datalayer:
    Image:      slfg92.rcs.de.alcatel-lucent.com:443/microfn/datalayer:latest
    Port:       4998/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:      100m
      memory:   200Mi
    Readiness:  tcp-socket :4998 delay=0s timeout=30s period=10s #success=1 #failure=10
    Environment:
      RIAK_CONNECT:        rk-mfn.knix-test.svc.cluster.local:8087
      DATALAYER_BIND:      0.0.0.0:4998
      ALL_DATALAYER_BIND:  dl-mfn1-0.datalayer.knix-test.svc.cluster.local:4998,dl-mfn1-1.datalayer.knix-test.svc.cluster.local:4998,dl-mfn1-2.datalayer.knix-test.svc.cluster.  local:4998
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-vbh6g (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-vbh6g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-vbh6g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods   anti-affinity rules, 2 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods   anti-affinity rules, 2 node(s) had taints that the pod didn't tolerate.

```

## Expected behavior

Surplus replicas can still be created (with a warning if necessary).

**Comment by ruichuan** [comment] 2020-06-16 11:52
knix requires at least 3 nodes for a riak cluster due to the requirement of achieving strong consistency in riak.

**Comment by iakkus** [comment] 2020-06-16 11:59
Yes, @ruichuan is right that we need 3 nodes for a riak cluster. However, I think the issue is still valid: 3 nodes of riak don't necessarily have to correspond to 3 physical nodes of the kubernetes cluster. Of course, loosening that podAntiAffinity role will also mean a looser fault-tolerance (i.e., if the physical node goes down, it will take down 2 of the riak nodes, potentially making it unstable).

@hpthai7: I'd think that this suggestion is very specific to the environment in question, though: you have 2 nodes in your cluster. My thought would be that you modify the relevant riak templates to remove or modify that rule for your own setup. As a general case, I doubt that we'd want to make it a general fix.

@manuelstein, @paarijaat: What do you think?

**Comment by ruichuan** [comment] 2020-06-16 12:07
Putting 3 replicas onto 2 physical nodes doesn't make them more reliable.
As a general rule, it's recommended to have at least 3 nodes for the
cluster.  Though, for this specific setup, it'd be worthwhile to modify
that rule..

**Comment by iakkus** [comment] 2020-06-16 12:34
Ah, I just noticed this is not about riak nodes; this is about datalayer service nodes! (That said, it may not be necessary for them to have a statefulset.)

@hpthai7: Data layer service needs to be running on every physical node for locality purposes. As a result, there is no point of having two replicas running on a single host. 

Even if the podAntiAffinity rule causes the replica to be in a pending state, that should not affect the platform. So I think your setup would still work without any changes.

**Comment by hpthai7** [comment] 2020-06-16 13:00
OK for the data layer service then. I meant that was just a suggestion for the service itself.

**Comment by iakkus** [comment] 2020-06-16 13:39
Great, thanks for the suggestion!

I think we might revisit the 'statefulset' requirement for the datalayer service, but that is not relevant for this particular issue. I am closing this issue now. If the data layer service seems to have a problem related to the 3rd (pending) replica, please re-open.

**Closed by iakkus** 2020-06-16 13:39 UTC
Labels: env/kubernetes
