### ISSUE TITLE
invalid knative deployments when using SDK functions to upload workflows 

### ISSUE THREAD

**Issue by ksatzke** [knix-microfunctions/knix#86] opened 2020-10-06 12:31 UTC
Using SDK functions to upload workflows to KNIX in some cases results in invalid helm deployments, error messages:

Revision creation failed with message: Revision.serving.knative.dev "xyz" is invalid: [metadata.labels: Invalid value: "wf-workflow-xyz": **must be no more than 63 characters** ... 

Likewise: 
Revision creation failed with message: Revision.serving.knative.dev "xyz" is invalid: [metadata.labels: Invalid value: "wf-workflow-abc/wf-workflow-xyz":   ... a valid label must be an empty string or consist of **alphanumeric characters,** '-', '_' or '.', and must start and end with an alphanumeric character ...

Problem seems to be related to preparing wfNameSanitized name in Management Service when creating a Kubernetes deployment

**Comment by iakkus** [comment] 2020-10-07 14:22
Is this reproducible via giving the workflow a very long name, so that the revision name will be longer than 63 characters? The example 'xyz' doesn't seem to actually create that long revision name. Or is it just an example?

**Comment by ksatzke** [comment] 2020-10-07 15:20
Hi Ekin,
quite right, I have given the workflow a long name >63 character which cause the problem reproducibly. Furthermore, the workflow name contained a “/” character, which causes problems even with shorter names.
The name was auto-generated by asl_Map state test script using paths and filenames of workflow definition files (which probably wasn’t a good idea from the beginning).
Shortening the path names and modifying/extending the wf actual name sanitation in deployWorkflow resolved the problem.

BR Klaus

**Comment by iakkus** [comment] 2020-10-09 08:26
I am a bit confused; is the fix entailing of 1) ensuring that workflow name does not contain "/" character (are there others?), 2) ensuring that the workflow name is of fixed length (at most 63?), 3) both?

Is this fixed in the 'develop' branch?

**Comment by ksatzke** [comment] 2020-10-09 08:58
as I have detected the bug during tests in the feature/GPU_support_extended branch with related PR upcoming soon I propose to fix it there.

**Comment by iakkus** [comment] 2020-10-09 09:08
I think this is a bug that we can backport to develop. Did you check that change in? Because I haven't seen any differences regarding the workflow name sanitization in deployWorkflow.

**Comment by ksatzke** [comment] 2020-10-09 09:12
The check for <63 chars is not yet checked in, the fix fo "/" character is.

**Comment by iakkus** [comment] 2020-10-09 10:01
I think it might be better if we were to allow certain characters in a workflow name, so that we will not have to figure out another character that was not handled later on.

I'd suggest we just allow only alphanumeric characters in workflow names, but recently we had a similar issue regarding AWS compatibility with regards to state names. Could this be a problem in that regard?

**Comment by ksatzke** [comment] 2020-10-09 10:17
The problem originates from the naming conventions and limitations defined in Kubernetes:

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#identifiers-and-names-in-kubernetes

rfc1035/rfc1123 label (DNS_LABEL): An alphanumeric (a-z, and 0-9) string, with a maximum length of 63 characters, with the '-' character allowed anywhere except the first or last character, suitable for use as a hostname or segment in a domain name
in fact k8s adapts

To my knowledge we do not provide checks on label names in our current KNIX in a systematic way (at least I did not see it). So, if we want to make KNIX bullet-proof in that regard, we need to check any label in K8S/KNative following the DNS name convention above.

BR Klaus

**Comment by ksatzke** [comment] 2020-10-09 10:41
By now I think this is an issue which should better be treated and fixed in develop branch, as you initially proposed.

Let’s discuss during today’s meeting. BR Klaus

**Closed** 2020-10-09 14:57 UTC
Labels: bug, env/kubernetes
